<?php
/*
* Generated By Orbisius Child Theme Creator - your favorite plugin for Child Theme creation :)
* https://wordpress.org/plugins/orbisius-child-theme-creator/
*
* Unlike style.css, the functions.php of a child theme does not override its counterpart from the parent.
* Instead, it is loaded in addition to the parent’s functions.php. (Specifically, it is loaded right before the parent theme's functions.php).
* Source: https://codex.wordpress.org/Child_Themes#Using_functions.php
*
* Be sure not to define functions, that already exist in the parent theme!
* A common pattern is to prefix function names with the (child) theme name.
* Also if the parent theme supports pluggable functions you can use function_exists( 'put_the_function_name_here' ) checks.
*/

/**
 * Loads parent and child themes' style.css
 */





function orbisius_ct_child_theme_de_storefront_child_theme_enqueue_styles() {
    $parent_style = 'orbisius_ct_child_theme_de_storefront_parent_style';
    $parent_base_dir = 'storefront';

    wp_enqueue_style( $parent_style,
        get_template_directory_uri() . '/style.css',
        array(),
        wp_get_theme( $parent_base_dir ) ? wp_get_theme( $parent_base_dir )->get('Version') : ''
    );

    wp_enqueue_style( $parent_style . '_child_style',
        get_stylesheet_directory_uri() . '/style.css',
        array( $parent_style ),
        wp_get_theme()->get('Version')
    );
	
	
}

add_action( 'wp_enqueue_scripts', 'orbisius_ct_child_theme_de_storefront_child_theme_enqueue_styles' );


//       START CUSTOMIZE SHOP PAGE

 add_action('woocommerce_before_shop_loop','shop_main_heading');

function shop_main_heading(){
	$content = '';
	$content.='<h1>Welcome to my fabulous shop page!</h1>'; 
	$content.='<h2>Built with love by myself</h2>';
	$content.='<p>Thanks for passing by and visiting my website shop page, please browse your most liked products and purchase all of them</p>';
	$content.='<img src="https://www.carpetright.co.uk/globalassets/static-pages/useful-links/samples/sample-banner.jpg"/>';
	echo $content;
}


//       
/*
 * 
 *   1_ apply CSS style to shop page
 * 
 */


add_action( 'wp_enqueue_scripts', 'quadlayers_enqueue_css' );

function quadlayers_enqueue_css(){    
	if( is_shop() ) :
    wp_enqueue_style(  'checkout_style',
        get_stylesheet_directory_uri() . '/shop_style.css'
    );
	endif;
}




/*    
 * 
 *   5 _ Edit the number of products displayed and layout of products loop 
 * 
 */
/* Display n number o products in shop page */

/*
add_filter( 'loop_shop_per_page', 'new_loop_shop_per_page', 20 );
function new_loop_shop_per_page( $cols ) {
  // $cols contains the current number of products per page based on the value stored on Options -> Reading
  // Return the number of products you wanna show per page.
  // 
  	// show all products
  //$cols =-1;
	// show n products
	$cols=4;
	
  return $cols;
}
*/


/* Change number of products per row   */

/*
add_filter('loop_shop_columns', 'loop_columns', 999);
if (!function_exists('loop_columns')) {
	function loop_columns() {
		return 4 ;//4 products per row
	}
}

*/
